[tool.poetry]
name = "prediction_pokemon_choice"
version = "0.1.0"
description = ""
authors = ["fufufukakaka <demonstrundum@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
pandas = "^2.1.3"
scikit-learn = "^1.3.2"
transformers = "^4.36.2"
cloudpickle = "^3.0.0"
torch = "^2.1.2"
datasets = "^2.16.1"
accelerate = "^0.26.1"

[tool.poetry.group.dev.dependencies]
ipython = "^8.3.0"
pytest = "^7.3.1"
pysen = "^0.10.4"
black = "^23.3.0"
isort = "^5.12.0"
flake8 = "^6.0.0"
mypy = "^1.3.0"

[[tool.poetry.source]]
name = "default"
url = "https://pypi.python.org/simple/"
priority = "default"

[tool.pysen]
version = "0.10"

[tool.pysen-cli]
settings_dir = "."

[tool.pysen.lint]
enable_black = true
enable_flake8 = true
enable_isort = true
enable_mypy = true
mypy_preset = "entry"
line_length = 88
py_version = "py310"
[[tool.pysen.lint.mypy_targets]]
  paths = ["src/"]

[tool.pysen.lint.source]
  includes = ["src/"]
  excludes = [".venv/"]


[tool.black] # automatically generated by pysen
# pysen ignores and overwrites any modifications
line-length = 88
target-version = ["py310"]

[tool.isort] # automatically generated by pysen
# pysen ignores and overwrites any modifications
default_section = "THIRDPARTY"
ensure_newline_before_comments = true
force_grid_wrap = 0
force_single_line = false
include_trailing_comma = true
line_length = 88
multi_line_output = 3
use_parentheses = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
